//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.UserProfilePictureManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProfilePictureManagementService.IUserProfilePictureManagementService", CallbackContract=typeof(LabyrinthClient.UserProfilePictureManagementService.IUserProfilePictureManagementServiceCallback))]
    public interface IUserProfilePictureManagementService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserProfilePictureManagementService/GetUserProfilePicture")]
        void GetUserProfilePicture(int userId, string path);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserProfilePictureManagementService/GetUserProfilePicture")]
        System.Threading.Tasks.Task GetUserProfilePictureAsync(int userId, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfilePictureManagementServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfilePictureManagementService/ReceiveProfilePicture", ReplyAction="http://tempuri.org/IUserProfilePictureManagementService/ReceiveProfilePictureResp" +
            "onse")]
        void ReceiveProfilePicture(int userId, byte[] dataImage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfilePictureManagementServiceChannel : LabyrinthClient.UserProfilePictureManagementService.IUserProfilePictureManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfilePictureManagementServiceClient : System.ServiceModel.DuplexClientBase<LabyrinthClient.UserProfilePictureManagementService.IUserProfilePictureManagementService>, LabyrinthClient.UserProfilePictureManagementService.IUserProfilePictureManagementService {
        
        public UserProfilePictureManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserProfilePictureManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserProfilePictureManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfilePictureManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfilePictureManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetUserProfilePicture(int userId, string path) {
            base.Channel.GetUserProfilePicture(userId, path);
        }
        
        public System.Threading.Tasks.Task GetUserProfilePictureAsync(int userId, string path) {
            return base.Channel.GetUserProfilePictureAsync(userId, path);
        }
    }
}
