//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.UserManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferUser", Namespace="http://schemas.datacontract.org/2004/07/UserManagementService")]
    [System.SerializableAttribute()]
    public partial class TransferUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabyrinthClient.UserManagementService.TransferCountry TransferCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((this.IdUserField.Equals(value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabyrinthClient.UserManagementService.TransferCountry TransferCountry {
            get {
                return this.TransferCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferCountryField, value) != true)) {
                    this.TransferCountryField = value;
                    this.RaisePropertyChanged("TransferCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferCountry", Namespace="http://schemas.datacontract.org/2004/07/CatalogManagementService")]
    [System.SerializableAttribute()]
    public partial class TransferCountry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementService.IUserManagement")]
    public interface IUserManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/addUser", ReplyAction="http://tempuri.org/IUserManagement/addUserResponse")]
        int addUser(LabyrinthClient.UserManagementService.TransferUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/addUser", ReplyAction="http://tempuri.org/IUserManagement/addUserResponse")]
        System.Threading.Tasks.Task<int> addUserAsync(LabyrinthClient.UserManagementService.TransferUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/userVerification", ReplyAction="http://tempuri.org/IUserManagement/userVerificationResponse")]
        LabyrinthClient.UserManagementService.TransferUser userVerification(LabyrinthClient.UserManagementService.TransferUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/userVerification", ReplyAction="http://tempuri.org/IUserManagement/userVerificationResponse")]
        System.Threading.Tasks.Task<LabyrinthClient.UserManagementService.TransferUser> userVerificationAsync(LabyrinthClient.UserManagementService.TransferUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/updateUser", ReplyAction="http://tempuri.org/IUserManagement/updateUserResponse")]
        int updateUser(LabyrinthClient.UserManagementService.TransferUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/updateUser", ReplyAction="http://tempuri.org/IUserManagement/updateUserResponse")]
        System.Threading.Tasks.Task<int> updateUserAsync(LabyrinthClient.UserManagementService.TransferUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/changeUserProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/changeUserProfilePictureResponse")]
        string changeUserProfilePicture(int userId, byte[] imagenData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/changeUserProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/changeUserProfilePictureResponse")]
        System.Threading.Tasks.Task<string> changeUserProfilePictureAsync(int userId, byte[] imagenData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/getUserProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/getUserProfilePictureResponse")]
        byte[] getUserProfilePicture(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/getUserProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/getUserProfilePictureResponse")]
        System.Threading.Tasks.Task<byte[]> getUserProfilePictureAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/verificateCode", ReplyAction="http://tempuri.org/IUserManagement/verificateCodeResponse")]
        bool verificateCode(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/verificateCode", ReplyAction="http://tempuri.org/IUserManagement/verificateCodeResponse")]
        System.Threading.Tasks.Task<bool> verificateCodeAsync(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/addVerificationCode", ReplyAction="http://tempuri.org/IUserManagement/addVerificationCodeResponse")]
        int addVerificationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/addVerificationCode", ReplyAction="http://tempuri.org/IUserManagement/addVerificationCodeResponse")]
        System.Threading.Tasks.Task<int> addVerificationCodeAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementChannel : LabyrinthClient.UserManagementService.IUserManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementClient : System.ServiceModel.ClientBase<LabyrinthClient.UserManagementService.IUserManagement>, LabyrinthClient.UserManagementService.IUserManagement {
        
        public UserManagementClient() {
        }
        
        public UserManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addUser(LabyrinthClient.UserManagementService.TransferUser user) {
            return base.Channel.addUser(user);
        }
        
        public System.Threading.Tasks.Task<int> addUserAsync(LabyrinthClient.UserManagementService.TransferUser user) {
            return base.Channel.addUserAsync(user);
        }
        
        public LabyrinthClient.UserManagementService.TransferUser userVerification(LabyrinthClient.UserManagementService.TransferUser user) {
            return base.Channel.userVerification(user);
        }
        
        public System.Threading.Tasks.Task<LabyrinthClient.UserManagementService.TransferUser> userVerificationAsync(LabyrinthClient.UserManagementService.TransferUser user) {
            return base.Channel.userVerificationAsync(user);
        }
        
        public int updateUser(LabyrinthClient.UserManagementService.TransferUser newUser) {
            return base.Channel.updateUser(newUser);
        }
        
        public System.Threading.Tasks.Task<int> updateUserAsync(LabyrinthClient.UserManagementService.TransferUser newUser) {
            return base.Channel.updateUserAsync(newUser);
        }
        
        public string changeUserProfilePicture(int userId, byte[] imagenData) {
            return base.Channel.changeUserProfilePicture(userId, imagenData);
        }
        
        public System.Threading.Tasks.Task<string> changeUserProfilePictureAsync(int userId, byte[] imagenData) {
            return base.Channel.changeUserProfilePictureAsync(userId, imagenData);
        }
        
        public byte[] getUserProfilePicture(string path) {
            return base.Channel.getUserProfilePicture(path);
        }
        
        public System.Threading.Tasks.Task<byte[]> getUserProfilePictureAsync(string path) {
            return base.Channel.getUserProfilePictureAsync(path);
        }
        
        public bool verificateCode(string email, string code) {
            return base.Channel.verificateCode(email, code);
        }
        
        public System.Threading.Tasks.Task<bool> verificateCodeAsync(string email, string code) {
            return base.Channel.verificateCodeAsync(email, code);
        }
        
        public int addVerificationCode(string email) {
            return base.Channel.addVerificationCode(email);
        }
        
        public System.Threading.Tasks.Task<int> addVerificationCodeAsync(string email) {
            return base.Channel.addVerificationCodeAsync(email);
        }
    }
}
