//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.UserManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferUser", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
    [System.SerializableAttribute()]
    public partial class TransferUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabyrinthClient.UserManagementService.TransferCountry TransferCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabyrinthClient.UserManagementService.TransferStats TransferStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((this.IdUserField.Equals(value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabyrinthClient.UserManagementService.TransferCountry TransferCountry {
            get {
                return this.TransferCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferCountryField, value) != true)) {
                    this.TransferCountryField = value;
                    this.RaisePropertyChanged("TransferCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabyrinthClient.UserManagementService.TransferStats TransferStats {
            get {
                return this.TransferStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferStatsField, value) != true)) {
                    this.TransferStatsField = value;
                    this.RaisePropertyChanged("TransferStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferCountry", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
    [System.SerializableAttribute()]
    public partial class TransferCountry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferStats", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
    [System.SerializableAttribute()]
    public partial class TransferStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesPlayed {
            get {
                return this.GamesPlayedField;
            }
            set {
                if ((this.GamesPlayedField.Equals(value) != true)) {
                    this.GamesPlayedField = value;
                    this.RaisePropertyChanged("GamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesWon {
            get {
                return this.GamesWonField;
            }
            set {
                if ((this.GamesWonField.Equals(value) != true)) {
                    this.GamesWonField = value;
                    this.RaisePropertyChanged("GamesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatId {
            get {
                return this.StatIdField;
            }
            set {
                if ((this.StatIdField.Equals(value) != true)) {
                    this.StatIdField = value;
                    this.RaisePropertyChanged("StatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
    [System.SerializableAttribute()]
    public partial class LabyrinthException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementService.IUserManagement", CallbackContract=typeof(LabyrinthClient.UserManagementService.IUserManagementCallback))]
    public interface IUserManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddUser", ReplyAction="http://tempuri.org/IUserManagement/AddUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/AddUserLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        int AddUser(LabyrinthClient.UserManagementService.TransferUser user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddUser", ReplyAction="http://tempuri.org/IUserManagement/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(LabyrinthClient.UserManagementService.TransferUser user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/VerificateUser", ReplyAction="http://tempuri.org/IUserManagement/VerificateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/VerificateUserLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        LabyrinthClient.UserManagementService.TransferUser VerificateUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/VerificateUser", ReplyAction="http://tempuri.org/IUserManagement/VerificateUserResponse")]
        System.Threading.Tasks.Task<LabyrinthClient.UserManagementService.TransferUser> VerificateUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateUser", ReplyAction="http://tempuri.org/IUserManagement/UpdateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/UpdateUserLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        int UpdateUser(LabyrinthClient.UserManagementService.TransferUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateUser", ReplyAction="http://tempuri.org/IUserManagement/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(LabyrinthClient.UserManagementService.TransferUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdatePassword", ReplyAction="http://tempuri.org/IUserManagement/UpdatePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/UpdatePasswordLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        int UpdatePassword(string pasword, string newPassword, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdatePassword", ReplyAction="http://tempuri.org/IUserManagement/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<int> UpdatePasswordAsync(string pasword, string newPassword, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteAllUsers", ReplyAction="http://tempuri.org/IUserManagement/DeleteAllUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/DeleteAllUsersLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        int DeleteAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteAllUsers", ReplyAction="http://tempuri.org/IUserManagement/DeleteAllUsersResponse")]
        System.Threading.Tasks.Task<int> DeleteAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ChangeUserProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/ChangeUserProfilePictureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/ChangeUserProfilePictureLabyrinthExceptionFaul" +
            "t", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        string ChangeUserProfilePicture(int userId, byte[] imagenData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ChangeUserProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/ChangeUserProfilePictureResponse")]
        System.Threading.Tasks.Task<string> ChangeUserProfilePictureAsync(int userId, byte[] imagenData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagement/GetUserProfilePicture")]
        void GetUserProfilePicture(int userId, string path);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserManagement/GetUserProfilePicture")]
        System.Threading.Tasks.Task GetUserProfilePictureAsync(int userId, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/VerificateCode", ReplyAction="http://tempuri.org/IUserManagement/VerificateCodeResponse")]
        bool VerificateCode(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/VerificateCode", ReplyAction="http://tempuri.org/IUserManagement/VerificateCodeResponse")]
        System.Threading.Tasks.Task<bool> VerificateCodeAsync(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddVerificationCode", ReplyAction="http://tempuri.org/IUserManagement/AddVerificationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/AddVerificationCodeLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        int AddVerificationCode(string email, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddVerificationCode", ReplyAction="http://tempuri.org/IUserManagement/AddVerificationCodeResponse")]
        System.Threading.Tasks.Task<int> AddVerificationCodeAsync(string email, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/IsEmailRegistered", ReplyAction="http://tempuri.org/IUserManagement/IsEmailRegisteredResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LabyrinthClient.UserManagementService.LabyrinthException), Action="http://tempuri.org/IUserManagement/IsEmailRegisteredLabyrinthExceptionFault", Name="LabyrinthException", Namespace="http://schemas.datacontract.org/2004/07/LabyrinthCommon")]
        bool IsEmailRegistered(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/IsEmailRegistered", ReplyAction="http://tempuri.org/IUserManagement/IsEmailRegisteredResponse")]
        System.Threading.Tasks.Task<bool> IsEmailRegisteredAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetRanking", ReplyAction="http://tempuri.org/IUserManagement/GetRankingResponse")]
        LabyrinthClient.UserManagementService.TransferUser[] GetRanking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetRanking", ReplyAction="http://tempuri.org/IUserManagement/GetRankingResponse")]
        System.Threading.Tasks.Task<LabyrinthClient.UserManagementService.TransferUser[]> GetRankingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ReceiveProfilePicture", ReplyAction="http://tempuri.org/IUserManagement/ReceiveProfilePictureResponse")]
        void ReceiveProfilePicture(int userId, byte[] dataImage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementChannel : LabyrinthClient.UserManagementService.IUserManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementClient : System.ServiceModel.DuplexClientBase<LabyrinthClient.UserManagementService.IUserManagement>, LabyrinthClient.UserManagementService.IUserManagement {
        
        public UserManagementClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int AddUser(LabyrinthClient.UserManagementService.TransferUser user, string password) {
            return base.Channel.AddUser(user, password);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(LabyrinthClient.UserManagementService.TransferUser user, string password) {
            return base.Channel.AddUserAsync(user, password);
        }
        
        public LabyrinthClient.UserManagementService.TransferUser VerificateUser(string email, string password) {
            return base.Channel.VerificateUser(email, password);
        }
        
        public System.Threading.Tasks.Task<LabyrinthClient.UserManagementService.TransferUser> VerificateUserAsync(string email, string password) {
            return base.Channel.VerificateUserAsync(email, password);
        }
        
        public int UpdateUser(LabyrinthClient.UserManagementService.TransferUser newUser) {
            return base.Channel.UpdateUser(newUser);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(LabyrinthClient.UserManagementService.TransferUser newUser) {
            return base.Channel.UpdateUserAsync(newUser);
        }
        
        public int UpdatePassword(string pasword, string newPassword, string email) {
            return base.Channel.UpdatePassword(pasword, newPassword, email);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePasswordAsync(string pasword, string newPassword, string email) {
            return base.Channel.UpdatePasswordAsync(pasword, newPassword, email);
        }
        
        public int DeleteAllUsers() {
            return base.Channel.DeleteAllUsers();
        }
        
        public System.Threading.Tasks.Task<int> DeleteAllUsersAsync() {
            return base.Channel.DeleteAllUsersAsync();
        }
        
        public string ChangeUserProfilePicture(int userId, byte[] imagenData) {
            return base.Channel.ChangeUserProfilePicture(userId, imagenData);
        }
        
        public System.Threading.Tasks.Task<string> ChangeUserProfilePictureAsync(int userId, byte[] imagenData) {
            return base.Channel.ChangeUserProfilePictureAsync(userId, imagenData);
        }
        
        public void GetUserProfilePicture(int userId, string path) {
            base.Channel.GetUserProfilePicture(userId, path);
        }
        
        public System.Threading.Tasks.Task GetUserProfilePictureAsync(int userId, string path) {
            return base.Channel.GetUserProfilePictureAsync(userId, path);
        }
        
        public bool VerificateCode(string email, string code) {
            return base.Channel.VerificateCode(email, code);
        }
        
        public System.Threading.Tasks.Task<bool> VerificateCodeAsync(string email, string code) {
            return base.Channel.VerificateCodeAsync(email, code);
        }
        
        public int AddVerificationCode(string email, string username) {
            return base.Channel.AddVerificationCode(email, username);
        }
        
        public System.Threading.Tasks.Task<int> AddVerificationCodeAsync(string email, string username) {
            return base.Channel.AddVerificationCodeAsync(email, username);
        }
        
        public bool IsEmailRegistered(string email) {
            return base.Channel.IsEmailRegistered(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailRegisteredAsync(string email) {
            return base.Channel.IsEmailRegisteredAsync(email);
        }
        
        public LabyrinthClient.UserManagementService.TransferUser[] GetRanking() {
            return base.Channel.GetRanking();
        }
        
        public System.Threading.Tasks.Task<LabyrinthClient.UserManagementService.TransferUser[]> GetRankingAsync() {
            return base.Channel.GetRankingAsync();
        }
    }
}
