//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Characters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Characters() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabyrinthClient.Properties.Characters", typeof(Characters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He is here for a new adventure..
        /// </summary>
        internal static string AdventurerDescriptionLabel {
            get {
                return ResourceManager.GetString("AdventurerDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adventurer.
        /// </summary>
        internal static string AdventurerNameLabel {
            get {
                return ResourceManager.GetString("AdventurerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He comes from a distant galaxy to explore the unknown..
        /// </summary>
        internal static string AlienDescriptionLabel {
            get {
                return ResourceManager.GetString("AlienDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alien.
        /// </summary>
        internal static string AlienNameLabel {
            get {
                return ResourceManager.GetString("AlienNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He is ready to track his prey with precision and skill..
        /// </summary>
        internal static string HunterDescriptionLabel {
            get {
                return ResourceManager.GetString("HunterDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hunter.
        /// </summary>
        internal static string HunterNameLabel {
            get {
                return ResourceManager.GetString("HunterNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From a land far, far away..
        /// </summary>
        internal static string KnightDescriptionLabel {
            get {
                return ResourceManager.GetString("KnightDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Knight.
        /// </summary>
        internal static string KnightNameLabel {
            get {
                return ResourceManager.GetString("KnightNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He moves silently, striking from the shadows..
        /// </summary>
        internal static string NinjaDescriptionLabel {
            get {
                return ResourceManager.GetString("NinjaDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninja.
        /// </summary>
        internal static string NinjaNameLabel {
            get {
                return ResourceManager.GetString("NinjaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He sails the seas in search of treasure and adventure..
        /// </summary>
        internal static string PirateDescriptionLabel {
            get {
                return ResourceManager.GetString("PirateDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pirate.
        /// </summary>
        internal static string PirateNameLabel {
            get {
                return ResourceManager.GetString("PirateNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a She is a real princess.
        /// </summary>
        internal static string PrincessDescriptionLabel {
            get {
                return ResourceManager.GetString("PrincessDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Princess.
        /// </summary>
        internal static string PrincessNameLabel {
            get {
                return ResourceManager.GetString("PrincessNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He is programmed to complete any mission without fail..
        /// </summary>
        internal static string RobotDescriptionLabel {
            get {
                return ResourceManager.GetString("RobotDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Robot.
        /// </summary>
        internal static string RobotNameLabel {
            get {
                return ResourceManager.GetString("RobotNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He seeks to uncover the secrets of the universe..
        /// </summary>
        internal static string ScientistDescriptionLabel {
            get {
                return ResourceManager.GetString("ScientistDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scientist.
        /// </summary>
        internal static string ScientistNameLabel {
            get {
                return ResourceManager.GetString("ScientistNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A master of illusions..
        /// </summary>
        internal static string WizzardDescriptionLabel {
            get {
                return ResourceManager.GetString("WizzardDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wizzard.
        /// </summary>
        internal static string WizzardNameLabel {
            get {
                return ResourceManager.GetString("WizzardNameLabel", resourceCulture);
            }
        }
    }
}
