//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabyrinthClient.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is registered already by another user.
        /// </summary>
        internal static string FailDuplicatedEmailMessage {
            get {
                return ResourceManager.GetString("FailDuplicatedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username is being used by another player.
        /// </summary>
        internal static string FailDuplicatedUsernameMessage {
            get {
                return ResourceManager.GetString("FailDuplicatedUsernameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have already sent a friend request to this user.
        /// </summary>
        internal static string FailFriendRequestDuplicated {
            get {
                return ResourceManager.GetString("FailFriendRequestDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is incorrect.
        /// </summary>
        internal static string FailIncorrectPasswordMessage {
            get {
                return ResourceManager.GetString("FailIncorrectPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect verification code.
        /// </summary>
        internal static string FailIncorrectVerificationCodeMessage {
            get {
                return ResourceManager.GetString("FailIncorrectVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is not valid. Make sure it is in the correct format..
        /// </summary>
        internal static string FailInvalidEmailMessage {
            get {
                return ResourceManager.GetString("FailInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be between 8 and 64 characters, and include at least one capital letter, one number, and one special character.
        /// </summary>
        internal static string FailInvalidPasswordMessage {
            get {
                return ResourceManager.GetString("FailInvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username must be between 3 and 50 characters and only letters and numbers..
        /// </summary>
        internal static string FailInvalidUsernameMessage {
            get {
                return ResourceManager.GetString("FailInvalidUsernameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby was not found.
        /// </summary>
        internal static string FailLobbyNotFoundMessage {
            get {
                return ResourceManager.GetString("FailLobbyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No countries found in the database.
        /// </summary>
        internal static string FailNoCountriesMessage {
            get {
                return ResourceManager.GetString("FailNoCountriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User has not been found.
        /// </summary>
        internal static string FailUserNotFoundMessage {
            get {
                return ResourceManager.GetString("FailUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to accept this friend request?.
        /// </summary>
        internal static string InfoAcceptRequestConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoAcceptRequestConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to quit the game?.
        /// </summary>
        internal static string InfoExitConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoExitConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile has been updated successfully.
        /// </summary>
        internal static string InfoProfileUpdatedMessage {
            get {
                return ResourceManager.GetString("InfoProfileUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reject this friend request?.
        /// </summary>
        internal static string InfoRejectRequestConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoRejectRequestConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has been accepted successfully.
        /// </summary>
        internal static string InfoRequestAcceptedMessage {
            get {
                return ResourceManager.GetString("InfoRequestAcceptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has been rejected successfully.
        /// </summary>
        internal static string InfoRequestRejectedMessage {
            get {
                return ResourceManager.GetString("InfoRequestRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have sent a friend request successfully.
        /// </summary>
        internal static string InfoSentFriendRequestMessage {
            get {
                return ResourceManager.GetString("InfoSentFriendRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to change your password?.
        /// </summary>
        internal static string InfoUpdatePasswordConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoUpdatePasswordConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to change your profile data?.
        /// </summary>
        internal static string InfoUpdateProfileConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoUpdateProfileConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Are you sure you want to update your profile picture?.
        /// </summary>
        internal static string InfoUpdateProfilePictureConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoUpdateProfilePictureConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your registration is complete, you can now log in.
        /// </summary>
        internal static string InfoUserRegisteredMessage {
            get {
                return ResourceManager.GetString("InfoUserRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent you a verification code to your email.
        /// </summary>
        internal static string InfoVerificationCodeSentMessage {
            get {
                return ResourceManager.GetString("InfoVerificationCodeSentMessage", resourceCulture);
            }
        }
    }
}
