//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabyrinthClient.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already another active session with this account.
        /// </summary>
        internal static string FailActiveSessionAlreadyMessage {
            get {
                return ResourceManager.GetString("FailActiveSessionAlreadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to connect to the chat.
        /// </summary>
        internal static string FailChatError {
            get {
                return ResourceManager.GetString("FailChatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the database. Please try again later.
        /// </summary>
        internal static string FailDatabaseConnectionMessage {
            get {
                return ResourceManager.GetString("FailDatabaseConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is registered already by another user.
        /// </summary>
        internal static string FailDuplicatedEmailMessage {
            get {
                return ResourceManager.GetString("FailDuplicatedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username is being used by another player.
        /// </summary>
        internal static string FailDuplicatedUsernameMessage {
            get {
                return ResourceManager.GetString("FailDuplicatedUsernameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the database. Please check your Internet connection or try again later.
        /// </summary>
        internal static string FailEntityConnectionMessage {
            get {
                return ResourceManager.GetString("FailEntityConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while managing friends.
        /// </summary>
        internal static string FailFriendManagementError {
            get {
                return ResourceManager.GetString("FailFriendManagementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have already sent a friend request to this user.
        /// </summary>
        internal static string FailFriendRequestDuplicatedMessage {
            get {
                return ResourceManager.GetString("FailFriendRequestDuplicatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t properly handle the profile photo correctly, please try again.
        /// </summary>
        internal static string FailHandleProfilePictureMessage {
            get {
                return ResourceManager.GetString("FailHandleProfilePictureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is incorrect.
        /// </summary>
        internal static string FailIncorrectPasswordMessage {
            get {
                return ResourceManager.GetString("FailIncorrectPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect verification code.
        /// </summary>
        internal static string FailIncorrectVerificationCodeMessage {
            get {
                return ResourceManager.GetString("FailIncorrectVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is not valid. Make sure it is in the correct format..
        /// </summary>
        internal static string FailInvalidEmailMessage {
            get {
                return ResourceManager.GetString("FailInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby code is invalid. It must follow the format XXX-XXX-XXX with uppercase letters and numbers.
        /// </summary>
        internal static string FailInvalidLobbyCodeMessage {
            get {
                return ResourceManager.GetString("FailInvalidLobbyCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movement is not allowed.
        /// </summary>
        internal static string FailInvalidMoveMessage {
            get {
                return ResourceManager.GetString("FailInvalidMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be between 8 and 64 characters, and include at least one capital letter, one number, and one special character.
        /// </summary>
        internal static string FailInvalidPasswordMessage {
            get {
                return ResourceManager.GetString("FailInvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username must be between 3 and 50 characters and only letters and numbers..
        /// </summary>
        internal static string FailInvalidUsernameMessage {
            get {
                return ResourceManager.GetString("FailInvalidUsernameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to enter the lobby. Please try again later.
        /// </summary>
        internal static string FailJoinToLobbyError {
            get {
                return ResourceManager.GetString("FailJoinToLobbyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to access the lobby.
        /// </summary>
        internal static string FailLobbyError {
            get {
                return ResourceManager.GetString("FailLobbyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby was not found.
        /// </summary>
        internal static string FailLobbyNotFoundMessage {
            get {
                return ResourceManager.GetString("FailLobbyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection to the server was lost. Therefore, you have been disconnected from the game. Please check your Internet connection and try again.
        /// </summary>
        internal static string FailLostConnectionMessage {
            get {
                return ResourceManager.GetString("FailLostConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No countries found in the database.
        /// </summary>
        internal static string FailNoCountriesMessage {
            get {
                return ResourceManager.GetString("FailNoCountriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred while connecting to the server. Please try again.
        /// </summary>
        internal static string FailNoServerCommunicationMessage {
            get {
                return ResourceManager.GetString("FailNoServerCommunicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We were unable to establish a connection to the server, please check your connection and try again.
        /// </summary>
        internal static string FailNotFoundEndPointMessage {
            get {
                return ResourceManager.GetString("FailNotFoundEndPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player is in game already.
        /// </summary>
        internal static string FailPlayerInGameMessage {
            get {
                return ResourceManager.GetString("FailPlayerInGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while loading player statistics..
        /// </summary>
        internal static string FailStatsNotFoundError {
            get {
                return ResourceManager.GetString("FailStatsNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The action has expired. Please try again.
        /// </summary>
        internal static string FailTimeOutMessage {
            get {
                return ResourceManager.GetString("FailTimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The profile photo must not be larger than 1 MB.
        /// </summary>
        internal static string FailTooLongProfilePictureMessage {
            get {
                return ResourceManager.GetString("FailTooLongProfilePictureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User has not been found.
        /// </summary>
        internal static string FailUserNotFoundMessage {
            get {
                return ResourceManager.GetString("FailUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to register.
        /// </summary>
        internal static string FailUserRegistrationError {
            get {
                return ResourceManager.GetString("FailUserRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to update the user.
        /// </summary>
        internal static string FailUserUpdatingError {
            get {
                return ResourceManager.GetString("FailUserUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to verify the user.
        /// </summary>
        internal static string FailUserVerficationMessage {
            get {
                return ResourceManager.GetString("FailUserVerficationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string GuestHasJoinedGameMessage {
            get {
                return ResourceManager.GetString("GuestHasJoinedGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string GuestHasLeftGame {
            get {
                return ResourceManager.GetString("GuestHasLeftGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to accept this friend request?.
        /// </summary>
        internal static string InfoAcceptRequestConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoAcceptRequestConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have received an invitation to join a game from.
        /// </summary>
        internal static string InfoAttendInvitationConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoAttendInvitationConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to quit the game?.
        /// </summary>
        internal static string InfoExitConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoExitConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has joined the game.
        /// </summary>
        internal static string InfoGuestHasJoinedGameMessage {
            get {
                return ResourceManager.GetString("InfoGuestHasJoinedGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has left the game.
        /// </summary>
        internal static string InfoGuestHasLeftGame {
            get {
                return ResourceManager.GetString("InfoGuestHasLeftGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have received a request to join a game, in order to join you need to leave the lobby. From:.
        /// </summary>
        internal static string InfoInvitationMessage {
            get {
                return ResourceManager.GetString("InfoInvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile has been updated successfully.
        /// </summary>
        internal static string InfoProfileUpdatedMessage {
            get {
                return ResourceManager.GetString("InfoProfileUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reject this friend request?.
        /// </summary>
        internal static string InfoRejectRequestConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoRejectRequestConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has been accepted successfully.
        /// </summary>
        internal static string InfoRequestAcceptedMessage {
            get {
                return ResourceManager.GetString("InfoRequestAcceptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has been rejected successfully.
        /// </summary>
        internal static string InfoRequestRejectedMessage {
            get {
                return ResourceManager.GetString("InfoRequestRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have sent a friend request successfully.
        /// </summary>
        internal static string InfoSentFriendRequestMessage {
            get {
                return ResourceManager.GetString("InfoSentFriendRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game has started.
        /// </summary>
        internal static string InfoStartGameMessage {
            get {
                return ResourceManager.GetString("InfoStartGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn of.
        /// </summary>
        internal static string InfoTurnMessage {
            get {
                return ResourceManager.GetString("InfoTurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to change your password?.
        /// </summary>
        internal static string InfoUpdatePasswordConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoUpdatePasswordConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to change your profile data?.
        /// </summary>
        internal static string InfoUpdateProfileConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoUpdateProfileConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Are you sure you want to update your profile picture?.
        /// </summary>
        internal static string InfoUpdateProfilePictureConfirmationMessage {
            get {
                return ResourceManager.GetString("InfoUpdateProfilePictureConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your registration is complete, you can now log in.
        /// </summary>
        internal static string InfoUserRegisteredMessage {
            get {
                return ResourceManager.GetString("InfoUserRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent you a verification code to your email.
        /// </summary>
        internal static string InfoVerificationCodeSentMessage {
            get {
                return ResourceManager.GetString("InfoVerificationCodeSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game is over. The winner is .
        /// </summary>
        internal static string InfoWinnerMessage {
            get {
                return ResourceManager.GetString("InfoWinnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have joined the game.
        /// </summary>
        internal static string InfoYouHaveJoinedTheGameMessage {
            get {
                return ResourceManager.GetString("InfoYouHaveJoinedTheGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string YouHaveJoinedTheGameMessage {
            get {
                return ResourceManager.GetString("YouHaveJoinedTheGameMessage", resourceCulture);
            }
        }
    }
}
