//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabyrinthClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string AddFriendButton {
            get {
                return ResourceManager.GetString("AddFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No advantage card yet.
        /// </summary>
        public static string AdvantageCardLabel {
            get {
                return ResourceManager.GetString("AdvantageCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adventurer.
        /// </summary>
        public static string AdventurerNameLabel {
            get {
                return ResourceManager.GetString("AdventurerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alien.
        /// </summary>
        public static string AlienNameLabel {
            get {
                return ResourceManager.GetString("AlienNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change profile picture.
        /// </summary>
        public static string ChangeProfilePictureButton {
            get {
                return ResourceManager.GetString("ChangeProfilePictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character selection.
        /// </summary>
        public static string CharacterSelectionLabel {
            get {
                return ResourceManager.GetString("CharacterSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classic.
        /// </summary>
        public static string ClassicComboBoxItem {
            get {
                return ResourceManager.GetString("ClassicComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile.
        /// </summary>
        public static string EditProfileButton {
            get {
                return ResourceManager.GetString("EditProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End turn.
        /// </summary>
        public static string EndTurnButton {
            get {
                return ResourceManager.GetString("EndTurnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends list.
        /// </summary>
        public static string FriendsListLabel {
            get {
                return ResourceManager.GetString("FriendsListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gameboard skin.
        /// </summary>
        public static string GameboardSkinLabel {
            get {
                return ResourceManager.GetString("GameboardSkinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string GlobalAcceptButton {
            get {
                return ResourceManager.GetString("GlobalAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string GlobalCancelButton {
            get {
                return ResourceManager.GetString("GlobalCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change character.
        /// </summary>
        public static string GlobalChangeCharacterButton {
            get {
                return ResourceManager.GetString("GlobalChangeCharacterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error.
        /// </summary>
        public static string GlobalConnectionErrorLabel {
            get {
                return ResourceManager.GetString("GlobalConnectionErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to connect to the server. Please check your internet connection..
        /// </summary>
        public static string GlobalConnectionErrorMessageText {
            get {
                return ResourceManager.GetString("GlobalConnectionErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email address .
        /// </summary>
        public static string GlobalEmailTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("GlobalEmailTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games played.
        /// </summary>
        public static string GlobalGamesPlayed {
            get {
                return ResourceManager.GetString("GlobalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won.
        /// </summary>
        public static string GlobalGamesWonLabel {
            get {
                return ResourceManager.GetString("GlobalGamesWonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        public static string GlobalInviteFriendButton {
            get {
                return ResourceManager.GetString("GlobalInviteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string GlobalJoinGame {
            get {
                return ResourceManager.GetString("GlobalJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby ID (e.g. xxx-xxx-xxx).
        /// </summary>
        public static string GlobalLobbyIdTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("GlobalLobbyIdTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string GlobalLobbyLabel {
            get {
                return ResourceManager.GetString("GlobalLobbyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby members.
        /// </summary>
        public static string GlobalLobbyMembersLabel {
            get {
                return ResourceManager.GetString("GlobalLobbyMembersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string GlobalLogin {
            get {
                return ResourceManager.GetString("GlobalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type here.
        /// </summary>
        public static string GlobalMessageTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("GlobalMessageTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string GlobalPasswordTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("GlobalPasswordTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players ready.
        /// </summary>
        public static string GlobalPlayersReadyLabel {
            get {
                return ResourceManager.GetString("GlobalPlayersReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signup.
        /// </summary>
        public static string GlobalSignup {
            get {
                return ResourceManager.GetString("GlobalSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.
        /// </summary>
        public static string GlobalUploadButton {
            get {
                return ResourceManager.GetString("GlobalUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string GlobalUsernameTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("GlobalUsernameTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string GlobalVerificationCodeTextBoxPlaceHolder {
            get {
                return ResourceManager.GetString("GlobalVerificationCodeTextBoxPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        public static string GlobalYouLabel {
            get {
                return ResourceManager.GetString("GlobalYouLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host game.
        /// </summary>
        public static string HostGameButton {
            get {
                return ResourceManager.GetString("HostGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hunter.
        /// </summary>
        public static string HunterNameLabel {
            get {
                return ResourceManager.GetString("HunterNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        public static string InviteFriendButton {
            get {
                return ResourceManager.GetString("InviteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join as guest.
        /// </summary>
        public static string JoinAsGuestTabItem {
            get {
                return ResourceManager.GetString("JoinAsGuestTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string JoinGameButton {
            get {
                return ResourceManager.GetString("JoinGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Knight.
        /// </summary>
        public static string KnightNameLabel {
            get {
                return ResourceManager.GetString("KnightNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby members.
        /// </summary>
        public static string LobbyMembersLabel {
            get {
                return ResourceManager.GetString("LobbyMembersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby settings.
        /// </summary>
        public static string LobbySettingsLabel {
            get {
                return ResourceManager.GetString("LobbySettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next treasure.
        /// </summary>
        public static string NextTreasureLabel {
            get {
                return ResourceManager.GetString("NextTreasureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninja.
        /// </summary>
        public static string NinjaNameLabel {
            get {
                return ResourceManager.GetString("NinjaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old password.
        /// </summary>
        public static string OldPasswordLabel {
            get {
                return ResourceManager.GetString("OldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pirate.
        /// </summary>
        public static string PirateNameLabel {
            get {
                return ResourceManager.GetString("PirateNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a She is a real princess.
        /// </summary>
        public static string PrincessDescriptionTextBlock {
            get {
                return ResourceManager.GetString("PrincessDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Princess.
        /// </summary>
        public static string PrincessNameLabel {
            get {
                return ResourceManager.GetString("PrincessNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking.
        /// </summary>
        public static string RankingLabel {
            get {
                return ResourceManager.GetString("RankingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Robot.
        /// </summary>
        public static string RobotNameLabel {
            get {
                return ResourceManager.GetString("RobotNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scientist.
        /// </summary>
        public static string ScientistNameLabel {
            get {
                return ResourceManager.GetString("ScientistNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select character.
        /// </summary>
        public static string SelectCharacterButton {
            get {
                return ResourceManager.GetString("SelectCharacterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select language.
        /// </summary>
        public static string SelectLanguageLabel {
            get {
                return ResourceManager.GetString("SelectLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends requests.
        /// </summary>
        public static string ShowFriendRequestsButton {
            get {
                return ResourceManager.GetString("ShowFriendRequestsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string ShowFriendsButton {
            get {
                return ResourceManager.GetString("ShowFriendsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treasures.
        /// </summary>
        public static string TreasuresLabel {
            get {
                return ResourceManager.GetString("TreasuresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update profile.
        /// </summary>
        public static string UpdateProfileLabel {
            get {
                return ResourceManager.GetString("UpdateProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volcano.
        /// </summary>
        public static string VolcanoComboBoxItem {
            get {
                return ResourceManager.GetString("VolcanoComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wizard.
        /// </summary>
        public static string WizardNameLabel {
            get {
                return ResourceManager.GetString("WizardNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
