//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.FriendsManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendsManagementService.IFriendsManagementService")]
    public interface IFriendsManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManagementService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsManagementService/SendFriendRequestResponse")]
        int SendFriendRequest(int userId, int friendId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendsManagementServiceChannel : LabyrinthClient.FriendsManagementService.IFriendsManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendsManagementServiceClient : System.ServiceModel.ClientBase<LabyrinthClient.FriendsManagementService.IFriendsManagementService>, LabyrinthClient.FriendsManagementService.IFriendsManagementService {
        
        public FriendsManagementServiceClient() {
        }
        
        public FriendsManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendsManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendsManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendsManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SendFriendRequest(int userId, int friendId) {
            return base.Channel.SendFriendRequest(userId, friendId);
        }
    }
}
