//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthClient.LobbyManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyManagementService.ILobbyManagementService", CallbackContract=typeof(LabyrinthClient.LobbyManagementService.ILobbyManagementServiceCallback))]
    public interface ILobbyManagementService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagementService/createLobby")]
        void createLobby();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagementService/createLobby")]
        System.Threading.Tasks.Task createLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagementService/joinToGame")]
        void joinToGame(string lobbyCode, string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManagementService/joinToGame")]
        System.Threading.Tasks.Task joinToGameAsync(string lobbyCode, string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagementServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManagementService/BroadcastCreated", ReplyAction="http://tempuri.org/ILobbyManagementService/BroadcastCreatedResponse")]
        void BroadcastCreated(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManagementService/BroadcastJoined", ReplyAction="http://tempuri.org/ILobbyManagementService/BroadcastJoinedResponse")]
        void BroadcastJoined(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagementServiceChannel : LabyrinthClient.LobbyManagementService.ILobbyManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyManagementServiceClient : System.ServiceModel.DuplexClientBase<LabyrinthClient.LobbyManagementService.ILobbyManagementService>, LabyrinthClient.LobbyManagementService.ILobbyManagementService {
        
        public LobbyManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagementServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void createLobby() {
            base.Channel.createLobby();
        }
        
        public System.Threading.Tasks.Task createLobbyAsync() {
            return base.Channel.createLobbyAsync();
        }
        
        public void joinToGame(string lobbyCode, string userName) {
            base.Channel.joinToGame(lobbyCode, userName);
        }
        
        public System.Threading.Tasks.Task joinToGameAsync(string lobbyCode, string userName) {
            return base.Channel.joinToGameAsync(lobbyCode, userName);
        }
    }
}
